jadwal/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'jadwal'

urlpatterns = [
	path('schedule/',views.CalendarView.as_view(), name='jadwal'),
	url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

stories/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls', namespace = 'tugas')),
    path('schedule/',include('jadwal.urls', namespace = 'jadwal')),
]

tugas/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from jadwal.views import CalendarView, event

app_name = 'tugas'

urlpatterns = [
	path('',views.index,name='index'),
	path('portfolio/',views.portfolio,name='portfolio'),
	path('about/',views.about,name='about'),
	path('email/',views.email,name='email'),
	path('temanbelajar/',views.temanbelajar,name='temanbelajar'),
]

jadwal/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from datetime import date, datetime
from django.utils import timezone

class Event(models.Model):
    event= models.CharField(max_length=255)
    category= models.CharField(max_length=255)
    place= models.CharField(max_length=255)
    day = models.DateField(u'Day of the event')
    start_time = models.TimeField(u'Starting time', help_text=u'hh:mm')
    end_time = models.TimeField(u'Final time', help_text=u'hh:mm')

    @property
    def get_html_url(self):
        url = reverse('jadwal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.event} </a>'

    def clean(self):
        if self.end_time <= self.start_time:
            raise ValidationError('Ending times must be after starting times')
 
        events = Event.objects.filter(day=self.day)
        if events.exists():
            for event in events:
                if self.check_overlap(event.start_time, event.end_time, self.start_time, self.end_time):
                    raise ValidationError('There is an overlap with another event: ' + str(event.day) + ', ' + str(event.start_time) + '-' + str(event.end_time))
    
    def check_overlap(self, fixed_start, fixed_end, new_start, new_end):
        overlap = False
        if new_start == fixed_end or new_end == fixed_start:    #edge case
            overlap = False
        elif (new_start >= fixed_start and new_start <= fixed_end) or (new_end >= fixed_start and new_end <= fixed_end): #innner limits
            overlap = True
        elif new_start <= fixed_start and new_end >= fixed_end: #outer limits
            overlap = True

        return overlap

tugas/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django.forms import ModelForm, DateInput, TimeInput
from jadwal.models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    widgets = {
        'day' : DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
        'start_time': TimeInput(attrs={'type': 'time'}),
        'end_time': TimeInput(attrs={'type': 'time'}),
    }
    fields = '__all__'

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    self.fields['day'].input_formats = ('%Y-%m-%d',)
    self.fields['start_time'].input_formats = ('%H:%M',)
    self.fields['end_time'].input_formats = ('%H:%M',)

tugas/forms.py
from django import forms

##Create your forms here

jadwal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.http import HttpResponseRedirect
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm


class CalendarView(generic.ListView):
    model = Event
    template_name = 'jadwal/jadwal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('jadwal:jadwal'))
    return render(request, 'jadwal/event.html', {'form': form})

tugas/views.py
from django.shortcuts import render,redirect

# Create your views here.
def index(request):
    return render(request,'pages/index.html',{})
def about(request):
    return render(request,'pages/about.html',{})
def email(request):
    return render(request,'pages/email.html',{})
def portfolio(request):
    return render(request,'pages/portfolio.html',{})
def temanbelajar(request):
    return render(request,'pages/temanbelajar.html',{})
def jadwal(request):
    return render(request,'jadwal/jadwal.html',{})

jadwal/templates/jadwal/event.html
{% extends 'pages/base.html' %} {% load static %} {% block page_content %}
<link rel="stylesheet" href="{% static 'css/calendarStyle.css' %}">
<body class="bg-cream text-roboto">
    <div class="d-flex justify-content-center">
        <h1 class="center-text" id="text-portfolio">EVENTS</h1>
    </div>
    <div class="padding-jadwal">
        <form method="post">
            {% csrf_token %}
            <table class="form form-table">
            {{ form }}
            <tr><td colspan="2">
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn-jadwal btn-info"> Submit </button>
            </div></td></tr>
            </table>
        </form>
    </div>
</body>
{% endblock %}

jadwal/templates/jadwal/jadwal.html
{% extends 'pages/base.html' %} {% load static %} {% block page_content %}
<link rel="stylesheet" href="{% static 'css/calendarStyle.css' %}">
<body class="bg-cream text-roboto">
    <div class="d-flex justify-content-center">
        <h1 class="center-text" id="text-portfolio">SCHEDULE</h1>
    </div>
    <div class="padding-jadwal">
        <div class="d-flex justify-content-between">
            <a class="btn-jadwal btn-info" href="{% url 'jadwal:jadwal' %}?{{ prev_month }}"> Previous Month </a>
            <a class="btn-jadwal btn-info" href="{% url 'jadwal:event_new' %}"> New Event </a>
            <a class="btn-jadwal btn-info" href="{% url 'jadwal:jadwal' %}?{{ next_month }}"> Next Month </a>
        </div>
        {{ calendar }}
    </div>
</body>
{% endblock %}

tugas/templates/pages/about.html
{% extends 'base.html' %} {% load static %} {%block page_content %}
<body id="body-portfolio">
  <div class="center-content">
    <div class="container-fluid">
      <h1 class="center-text big-text" id="text-portfolio">KNOW ME</h1>
      <h1 class="center-text big-text" id="text-portfolio">A LITTLE MORE</h1>
      <br><br>
      <a href="{% url 'tugas:email' %}">
        <button type="button" class="btn btn-outline-primary"><i class="far fa-envelope"></i></button>
      </a>
      <a href="https://www.linkedin.com/in/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-linkedin-in"></i></button>
      </a>
      <a href="https://www.behance.net/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-behance"></i></i></button>
      </a>
    </div>
  </div>
  <br><br><br><br><br>
  <div class="picbox">
    <div class="d-flex justify-content-center">
        <img src="{% static 'assets/bel.jpg' %}" class="card-img">
        <div class="d-flex align-items-center" id="text-index">
          <div class="flex-column">
              <h4 class="center-text">Hi, I'm Nabila!</h4>
              <h5 id="text-btn-portfolio">UI/UX enthusiast and a perfectly ordinary<br>college student living in Jakarta.</h5>
          </div>
        </div>
    </div>
  </div>
  <div class="resume btn-portfolio">
      <div class="d-flex justify-content-center">
        <h2 class="center-text">RESUME</h2>
      </div>
      <div class="flex-column" id="resume-margin">
          <div class="d-flex" id="text-btn-portfolio" style="margin-bottom: 2rem"> 
              <div class="row">
                <div class="cl-6">
                <div><h4>SKILLS</h4></div>
                </div>
                <div class="cl-6">
                  <div class="flex-column" style="margin-left: 15rem">
                    <div id="bold-text">• Adobe Photoshop, Illustrator, and Experience Design </div>
                    <div id="bold-text">• Java, Python</div>
                  </div>
                </div>
              </div> 
          </div>
          <div class="d-flex" id="text-btn-portfolio" style="margin-bottom: 2rem">
            <div class="row">
              <div class="cl-6">
              <div><h4>EXPERIENCE</h4></div>
              </div>
              <div class="cl-6">
                <div class="flex-column" style="margin-left: 11rem">
                  <div id="bold-text">Staff of Community Service Department</div>
                  <div>BEM Fasilkom UI<br>Feb 2019 - Present</div>
                  <div id="bold-text">Staff of Digital Marketing</div>
                  <div>COMPFEST<br>Feb 2019 - Present</div>
                  <div id="bold-text">Staff of Event Division</div>
                  <div>BETIS 2019<br>Jan 2019 - May 2019</div>
                  <div id="bold-text">Staff of Design Division</div>
                  <div>9th OLIM UI<br>Sep 2018 - Nov 2018</div>
                </div>
              </div>
            </div> 
          </div>
          <div class="d-flex" id="text-btn-portfolio" style="margin-bottom: 2rem"> 
              <div class="row">
                <div class="cl-6">
                <div><h4>EDUCATION</h4></div>
                </div>
                <div class="cl-6">
                  <div class="flex-column" style="margin-left: 11.5rem">
                    <div id="bold-text">University of Indonesia</div>
                    <div>Bachelor’s degree, Computer Science<br>2018 - 2022</div>
                  </div>
                </div>
              </div>
          </div>
          <div class="d-flex" id="text-btn-portfolio" style="margin-bottom: 2rem"> 
              <div class="row">
                <div class="cl-6">
                <div><h4>ACHIEVEMENT</h4></div>
                </div>
                <div class="cl-6">
                  <div class="flex-column" style="margin-left: 9.4rem">
                    <div id="bold-text">Top 10 Finalist, Technovation Arkavidia 5.0</div>
                    <div>Bandung Institute of Technology<br>Feb 2019</div>
                  </div>
                </div>
              </div>
          </div>
          
      <div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock %}

tugas/templates/pages/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <title>Nabila Ayu</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container-fluid">
        <a class="navbar-brand" id="text-portfolio" href="{% url 'tugas:index' %}">NABILA AYU</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <a class="nav-link" id="text-portfolio" href="{% url 'tugas:portfolio' %}">PORTFOLIO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="text-portfolio" href="{% url 'jadwal:jadwal' %}">SCHEDULE</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" id="text-portfolio" href="{% url 'tugas:about' %}">ABOUT</a>
            </li>
        </ul>
        </div>
        </div>
    </nav>
</body>
{% block page_content %} {% endblock %}
</html>

tugas/templates/pages/email.html
{% extends 'base.html' %} {% load static %} {%block page_content %}
<body id="body-portfolio">
  <div class="center-content">
    <div class="container-fluid">
      <h2 class="center-text text-grey">You can find me at</h2>
      <h1 class="center-text" id="text-portfolio">NABILADEWANTI@GMAIL.COM</h1>
      <br>
      <a href="{% url 'tugas:email' %}">
        <button type="button" class="btn btn-outline-primary"><i class="far fa-envelope"></i></button>
      </a>
      <a href="https://www.linkedin.com/in/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-linkedin-in"></i></button>
      </a>
      <a href="https://www.behance.net/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-behance"></i></i></button>
      </a>
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock %}

tugas/templates/pages/index.html
{% extends 'base.html' %} {% load static %} {%block page_content %}
<body id="body-portfolio">
  <div class="center-content">
    <div class="container-fluid">
      <h1 class="center-text big-text" id="text-portfolio">UI/UX</h1>
      <h1 class="center-text big-text" id="text-portfolio">DESIGNER</h1>
      <h6 class="center-text" id="text-portfolio">ENTHUSIAST</h6>
      <br>
      <a href="{% url 'tugas:email' %}">
        <button type="button" class="btn btn-outline-primary"><i class="far fa-envelope"></i></button>
      </a>
      <a href="https://www.linkedin.com/in/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-linkedin-in"></i></button>
      </a>
      <a href="https://www.behance.net/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-behance"></i></i></button>
      </a>
    </div>
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock %}

tugas/templates/pages/portfolio.html
{% extends 'base.html' %} {% load static %} {%block page_content %}
<body id="body-portfolio">
  <div class="center-content">
    <div class="container-fluid">
      <h1 class="center-text big-text" id="text-portfolio">SOME OF</h1>
      <h1 class="center-text big-text" id="text-portfolio">MY WORKS</h1>
      <br><br>
      <a href="{% url 'tugas:email' %}">
        <button type="button" class="btn btn-outline-primary"><i class="far fa-envelope"></i></button>
      </a>
      <a href="https://www.linkedin.com/in/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-linkedin-in"></i></button>
      </a>
      <a href="https://www.behance.net/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-behance"></i></i></button>
      </a>
    </div>
  </div>
  <br><br><br><br><br>
  <div class="card" id="text-portfolio text-btn-portfolio">
    <img src="{% static 'assets/temanbelajar.jpg' %}" class="card-img">
    <div class="card-img-overlay container1">
      <a href="{% url 'tugas:temanbelajar' %}">
        <h1 class="btn-outline-primary btn-portfolio big-text">TemanBelajar</h1>
      </a>
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock %}

tugas/templates/pages/temanbelajar.html
{% extends 'base.html' %} {% load static %} {%block page_content %}
<body id="body-tb">
  <div class="tb-margin">
    <div class="text-align-center" id="text-btn-portfolio">
        <h1 class="big-text" id="text-portfolio">TemanBelajar</h1>
        <h4 id="text-portfolio">Dari Siswa untuk Siswa</h4>
    </div>
  </div>
  <div class="text-align-center textboxtb" id="text-btn-portfolio">
    <p id="text-index"><b>TemanBelajar</b> was the brainchild of an education themed<br>business plan competition. My teammates and I created the idea<br>of a student-to-student tutoring app. Wonderfully, I got the<br>chance to develop the app’s UI and poster.</p>
  </div>
  <div class="d-flex justify-content-center picrow-margin" id="text-btn-portfolio">
    <div class="container-fluid">
    <div class="row">
    <div class="polaroid">
      <img src="{% static 'assets/stack.jpg' %}" alt="5 Terre" style="width:100%">
      <div class="container" id="text-portfolio">
      <p>Posters</p>
      </div>
    </div>
    <div class="polaroid">
      <img src="{% static 'assets/kumpul.png' %}" alt="5 Terre" style="width:100%">
      <div class="container" id="text-portfolio">
      <p>Mascots</p>
      </div>
    </div> 
    <div class="polaroid">
      <img src="{% static 'assets/satu.jpg' %}" alt="5 Terre" style="width:100%">
      <div class="container" id="text-portfolio">
      <p>Front Page</p>
      </div>
    </div> 
    </div>
    </div>
  </div>
  <div id="bottom-color">
    <div class="d-flex justify-content-center" id="bottom-margin">
      <a href="{% url 'tugas:email' %}">
        <button type="button" class="btn btn-outline-primary"><i class="far fa-envelope"></i></button>
      </a>
      <a href="https://www.linkedin.com/in/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-linkedin-in"></i></button>
      </a>
      <a href="https://www.behance.net/nabilaayu">
        <button type="button" class="btn btn-outline-primary"><i class="fab fa-behance"></i></i></button>
      </a>
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
{% endblock %}